// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e4f5f525-1e21-4102-84b5-3485348b3fce";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onFacilityScaleChange();
void onFanDutyPctChange();
void onSimSpeedHoursPerMinChange();
void onSolarSimPctChange();
void onSimJumpHourChange();
void onTariffProfileChange();
void onAutoControlChange();
void onAutoModeChange();
void onFaultResetChange();
void onRelay1OnChange();
void onRelay2OnChange();
void onResetEnergyCostChange();
void onSimRunChange();
void onSolarSimEnableChange();
void onSolarSimEnabledChange();

String emsState;
String faultReason;
String rateBand;
String simTime12h;
float batteryCurrent_A;
float batteryPower_W;
float batterySOC_pct;
float batteryVoltage_V;
float costActual_USD;
float costBaseline_USD;
float costSavings_USD;
float dayCostActual_USD;
float dayCostBaseline_USD;
float dayEnergy_kWh;
float dayGrid_kWh;
float dayRenew_kWh;
float daySavings_USD;
float energyGrid_kWh;
float energyRenew_kWh;
float energyTotal_kWh;
float facilityScale;
float fanDuty_pct;
float grid_bus_v;
float gridCurrent_A;
float grid_power_mw;
float gridPower_W;
float gridPrice_dperkWh;
float gridVoltage_V;
float loadCurrent_A;
float loadPower_W;
float loadVoltage_V;
float simSpeed_hoursPerMin;
float solarCurrent_A;
float solarPower_W;
float solarSim_pct;
float solarVoltage_V;
int fanRPM;
int simDay;
int simHour;
int simJumpHour;
int tariffProfile;
bool autoControl;
bool autoMode;
bool faultActive;
bool faultReset;
bool relay1_on;
bool relay2_on;
bool resetEnergyCost;
bool simRun;
bool solarSim_enable;
bool solarSimEnabled;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(emsState, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(faultReason, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(rateBand, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(simTime12h, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(batteryCurrent_A, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(batteryPower_W, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(batterySOC_pct, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(batteryVoltage_V, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(costActual_USD, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(costBaseline_USD, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(costSavings_USD, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(dayCostActual_USD, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(dayCostBaseline_USD, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(dayEnergy_kWh, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(dayGrid_kWh, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(dayRenew_kWh, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(daySavings_USD, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(energyGrid_kWh, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(energyRenew_kWh, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(energyTotal_kWh, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(facilityScale, READWRITE, ON_CHANGE, onFacilityScaleChange);
  ArduinoCloud.addProperty(fanDuty_pct, READWRITE, ON_CHANGE, onFanDutyPctChange);
  ArduinoCloud.addProperty(grid_bus_v, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(gridCurrent_A, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(grid_power_mw, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(gridPower_W, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(gridPrice_dperkWh, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(gridVoltage_V, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(loadCurrent_A, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(loadPower_W, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(loadVoltage_V, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(simSpeed_hoursPerMin, READWRITE, ON_CHANGE, onSimSpeedHoursPerMinChange, 30);
  ArduinoCloud.addProperty(solarCurrent_A, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(solarPower_W, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(solarSim_pct, READWRITE, ON_CHANGE, onSolarSimPctChange);
  ArduinoCloud.addProperty(solarVoltage_V, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(fanRPM, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(simDay, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(simHour, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(simJumpHour, READWRITE, ON_CHANGE, onSimJumpHourChange);
  ArduinoCloud.addProperty(tariffProfile, READWRITE, 2 * SECONDS, onTariffProfileChange);
  ArduinoCloud.addProperty(autoControl, READWRITE, 1 * SECONDS, onAutoControlChange);
  ArduinoCloud.addProperty(autoMode, READWRITE, ON_CHANGE, onAutoModeChange);
  ArduinoCloud.addProperty(faultActive, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(faultReset, READWRITE, ON_CHANGE, onFaultResetChange);
  ArduinoCloud.addProperty(relay1_on, READWRITE, ON_CHANGE, onRelay1OnChange);
  ArduinoCloud.addProperty(relay2_on, READWRITE, ON_CHANGE, onRelay2OnChange);
  ArduinoCloud.addProperty(resetEnergyCost, READWRITE, ON_CHANGE, onResetEnergyCostChange);
  ArduinoCloud.addProperty(simRun, READWRITE, ON_CHANGE, onSimRunChange);
  ArduinoCloud.addProperty(solarSim_enable, READWRITE, ON_CHANGE, onSolarSimEnableChange);
  ArduinoCloud.addProperty(solarSimEnabled, READWRITE, 1 * SECONDS, onSolarSimEnabledChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
